"""
LearnMate — Sample Course Data
Used to seed the database on first run.
"""

SAMPLE_COURSES = [
    # ── Artificial Intelligence / Machine Learning ──────────────────────────
    {
        "title": "Machine Learning Specialization",
        "description": "Master the fundamentals of machine learning with Andrew Ng. Covers supervised, unsupervised, and reinforcement learning.",
        "category": "Machine Learning",
        "domain": "Artificial Intelligence",
        "level": "beginner",
        "duration_hours": 87.0,
        "xp_reward": 500,
        "provider": "Coursera (DeepLearning.AI)",
        "url": "https://www.coursera.org/specializations/machine-learning-introduction",
        "tags": "machine learning,python,numpy,scikit-learn,supervised learning",
        "prerequisites": "",
        "rating": 4.9,
        "enrollments": 950000,
    },
    {
        "title": "Deep Learning Specialization",
        "description": "Build and train deep neural networks. Covers CNNs, RNNs, LSTMs, transformers, and NLP fundamentals.",
        "category": "Deep Learning",
        "domain": "Artificial Intelligence",
        "level": "intermediate",
        "duration_hours": 120.0,
        "xp_reward": 700,
        "provider": "Coursera (DeepLearning.AI)",
        "url": "https://www.coursera.org/specializations/deep-learning",
        "tags": "deep learning,neural networks,tensorflow,keras,NLP,computer vision",
        "prerequisites": "Machine Learning basics,Python",
        "rating": 4.8,
        "enrollments": 720000,
    },
    {
        "title": "IBM AI Engineering Professional Certificate",
        "description": "Master AI engineering skills including machine learning, deep learning, and neural networks using IBM tools.",
        "category": "AI Engineering",
        "domain": "Artificial Intelligence",
        "level": "intermediate",
        "duration_hours": 180.0,
        "xp_reward": 800,
        "provider": "Coursera (IBM)",
        "url": "https://www.coursera.org/professional-certificates/ai-engineer",
        "tags": "AI,IBM Watson,deep learning,machine learning,Python",
        "prerequisites": "Python programming",
        "rating": 4.6,
        "enrollments": 300000,
    },
    # ── Data Science ─────────────────────────────────────────────────────────
    {
        "title": "IBM Data Science Professional Certificate",
        "description": "Launch your career in data science with hands-on labs, real datasets, and IBM Cloud tools.",
        "category": "Data Science",
        "domain": "Data Science",
        "level": "beginner",
        "duration_hours": 160.0,
        "xp_reward": 600,
        "provider": "Coursera (IBM)",
        "url": "https://www.coursera.org/professional-certificates/ibm-data-science",
        "tags": "data science,python,SQL,data visualisation,machine learning",
        "prerequisites": "",
        "rating": 4.6,
        "enrollments": 650000,
    },
    {
        "title": "Data Analysis with Python",
        "description": "Learn data wrangling, analysis, and visualisation using Pandas, NumPy, and Matplotlib.",
        "category": "Data Analysis",
        "domain": "Data Science",
        "level": "beginner",
        "duration_hours": 18.0,
        "xp_reward": 200,
        "provider": "freeCodeCamp",
        "url": "https://www.freecodecamp.org/learn/data-analysis-with-python/",
        "tags": "python,pandas,numpy,matplotlib,data analysis",
        "prerequisites": "Basic Python",
        "rating": 4.7,
        "enrollments": 500000,
    },
    {
        "title": "Applied Data Science with Python Specialization",
        "description": "Apply text mining, social network analysis, applied plotting, and ML in Python.",
        "category": "Data Science",
        "domain": "Data Science",
        "level": "intermediate",
        "duration_hours": 80.0,
        "xp_reward": 450,
        "provider": "Coursera (University of Michigan)",
        "url": "https://www.coursera.org/specializations/data-science-python",
        "tags": "python,data science,NLP,machine learning,matplotlib",
        "prerequisites": "Python programming",
        "rating": 4.5,
        "enrollments": 420000,
    },
    # ── Web Development ───────────────────────────────────────────────────────
    {
        "title": "The Odin Project — Full Stack",
        "description": "Free, open-source curriculum for full-stack web development. Covers HTML, CSS, JavaScript, Ruby on Rails, and Node.js.",
        "category": "Full Stack",
        "domain": "Web Development",
        "level": "beginner",
        "duration_hours": 300.0,
        "xp_reward": 900,
        "provider": "The Odin Project",
        "url": "https://www.theodinproject.com",
        "tags": "web development,HTML,CSS,JavaScript,Node.js,Ruby on Rails",
        "prerequisites": "",
        "rating": 4.9,
        "enrollments": 400000,
    },
    {
        "title": "React — The Complete Guide 2024",
        "description": "Master React including Hooks, Redux, React Router, Next.js, and deployment.",
        "category": "Frontend",
        "domain": "Web Development",
        "level": "intermediate",
        "duration_hours": 68.0,
        "xp_reward": 400,
        "provider": "Udemy (Maximilian Schwarzmüller)",
        "url": "https://www.udemy.com/course/react-the-complete-guide-incl-redux/",
        "tags": "React,JavaScript,Redux,Next.js,frontend",
        "prerequisites": "HTML,CSS,JavaScript basics",
        "rating": 4.7,
        "enrollments": 850000,
    },
    {
        "title": "Node.js, Express, MongoDB Bootcamp",
        "description": "Build a complete REST API with Node.js, Express, and MongoDB including authentication and deployment.",
        "category": "Backend",
        "domain": "Web Development",
        "level": "intermediate",
        "duration_hours": 42.0,
        "xp_reward": 350,
        "provider": "Udemy (Jonas Schmedtmann)",
        "url": "https://www.udemy.com/course/nodejs-express-mongodb-bootcamp/",
        "tags": "Node.js,Express,MongoDB,REST API,backend",
        "prerequisites": "JavaScript fundamentals",
        "rating": 4.8,
        "enrollments": 340000,
    },
    # ── Cloud Computing ───────────────────────────────────────────────────────
    {
        "title": "AWS Certified Solutions Architect – Associate",
        "description": "Prepare for the AWS SAA-C03 exam. Covers VPC, EC2, S3, RDS, Lambda, and more.",
        "category": "Cloud",
        "domain": "Cloud Computing",
        "level": "intermediate",
        "duration_hours": 55.0,
        "xp_reward": 500,
        "provider": "Udemy (Stephane Maarek)",
        "url": "https://www.udemy.com/course/aws-certified-solutions-architect-associate-saa-c03/",
        "tags": "AWS,cloud,solutions architect,EC2,S3,Lambda",
        "prerequisites": "Basic networking concepts",
        "rating": 4.7,
        "enrollments": 620000,
    },
    {
        "title": "Google Cloud Professional Data Engineer",
        "description": "Prepare for the GCP Professional Data Engineer certification. Covers BigQuery, Dataflow, Pub/Sub, and ML on GCP.",
        "category": "Cloud Data",
        "domain": "Cloud Computing",
        "level": "advanced",
        "duration_hours": 40.0,
        "xp_reward": 600,
        "provider": "Coursera (Google)",
        "url": "https://www.coursera.org/professional-certificates/gcp-data-engineering",
        "tags": "GCP,BigQuery,Dataflow,cloud data,data engineering",
        "prerequisites": "Data engineering basics,SQL",
        "rating": 4.5,
        "enrollments": 180000,
    },
    # ── Cybersecurity ─────────────────────────────────────────────────────────
    {
        "title": "Google Cybersecurity Professional Certificate",
        "description": "Prepare for an entry-level cybersecurity role. Covers networking, Linux, SQL, Python, and security tools.",
        "category": "Cybersecurity",
        "domain": "Cybersecurity",
        "level": "beginner",
        "duration_hours": 120.0,
        "xp_reward": 550,
        "provider": "Coursera (Google)",
        "url": "https://www.coursera.org/professional-certificates/google-cybersecurity",
        "tags": "cybersecurity,networking,Linux,Python,SIEM,threat analysis",
        "prerequisites": "",
        "rating": 4.8,
        "enrollments": 320000,
    },
    # ── DevOps ────────────────────────────────────────────────────────────────
    {
        "title": "DevOps Bootcamp — Nana",
        "description": "Complete DevOps course covering Docker, Kubernetes, Jenkins, Terraform, and GitLab CI/CD.",
        "category": "DevOps",
        "domain": "DevOps",
        "level": "intermediate",
        "duration_hours": 50.0,
        "xp_reward": 450,
        "provider": "TechWorld with Nana",
        "url": "https://www.techworld-with-nana.com/devops-bootcamp",
        "tags": "DevOps,Docker,Kubernetes,CI/CD,Terraform,Jenkins",
        "prerequisites": "Linux basics,networking",
        "rating": 4.8,
        "enrollments": 250000,
    },
    # ── Mobile Development ────────────────────────────────────────────────────
    {
        "title": "Flutter & Dart — The Complete Guide",
        "description": "Build cross-platform iOS and Android apps with Flutter and Dart from scratch.",
        "category": "Mobile",
        "domain": "Mobile Development",
        "level": "beginner",
        "duration_hours": 42.0,
        "xp_reward": 400,
        "provider": "Udemy (Maximilian Schwarzmüller)",
        "url": "https://www.udemy.com/course/learn-flutter-dart-to-build-ios-android-apps/",
        "tags": "Flutter,Dart,iOS,Android,mobile development",
        "prerequisites": "Basic programming knowledge",
        "rating": 4.7,
        "enrollments": 290000,
    },
    # ── UI/UX Design ──────────────────────────────────────────────────────────
    {
        "title": "Google UX Design Professional Certificate",
        "description": "Learn UX design end-to-end: research, wireframing, prototyping, and Figma.",
        "category": "UX Design",
        "domain": "UI/UX Design",
        "level": "beginner",
        "duration_hours": 200.0,
        "xp_reward": 550,
        "provider": "Coursera (Google)",
        "url": "https://www.coursera.org/professional-certificates/google-ux-design",
        "tags": "UX design,Figma,prototyping,user research,wireframing",
        "prerequisites": "",
        "rating": 4.8,
        "enrollments": 420000,
    },
    # ── Python ────────────────────────────────────────────────────────────────
    {
        "title": "Python for Everybody Specialization",
        "description": "Learn to program and analyse data with Python. Perfect for absolute beginners.",
        "category": "Programming",
        "domain": "Python",
        "level": "beginner",
        "duration_hours": 60.0,
        "xp_reward": 300,
        "provider": "Coursera (University of Michigan)",
        "url": "https://www.coursera.org/specializations/python",
        "tags": "python,programming,data structures,web scraping,databases",
        "prerequisites": "",
        "rating": 4.8,
        "enrollments": 1200000,
    },
    {
        "title": "100 Days of Code — Python Bootcamp",
        "description": "Build 100 projects in 100 days covering automation, games, web apps, data science, and ML.",
        "category": "Programming",
        "domain": "Python",
        "level": "intermediate",
        "duration_hours": 60.0,
        "xp_reward": 500,
        "provider": "Udemy (Dr. Angela Yu)",
        "url": "https://www.udemy.com/course/100-days-of-code/",
        "tags": "python,automation,web scraping,Flask,data science",
        "prerequisites": "Basic Python",
        "rating": 4.7,
        "enrollments": 980000,
    },
    # ── Blockchain ────────────────────────────────────────────────────────────
    {
        "title": "Blockchain Specialization",
        "description": "Design and implement smart contracts with Ethereum and Solidity. Build decentralised applications.",
        "category": "Blockchain",
        "domain": "Blockchain",
        "level": "intermediate",
        "duration_hours": 60.0,
        "xp_reward": 500,
        "provider": "Coursera (University at Buffalo)",
        "url": "https://www.coursera.org/specializations/blockchain",
        "tags": "blockchain,Ethereum,Solidity,smart contracts,DeFi",
        "prerequisites": "OOP programming basics",
        "rating": 4.4,
        "enrollments": 120000,
    },
]
